<?php


return [
    'access' => [

        'dashboard-list' => 'dashboard_list',
        'dashboard-add' => 'dashboard_add',
        'dashboard-edit' => 'dashboard_edit',
        'dashboard-delete' => 'dashboard_delete',

        'job_emails-list' => 'job_emails_list',
        'job_emails-add' => 'job_emails_add',
        'job_emails-edit' => 'job_emails_edit',
        'job_emails-delete' => 'job_emails_delete',

//        'news-list' => 'news_list',
//        'news-add' => 'news_add',
//        'news-edit' => 'news_edit',
//        'news-delete' => 'news_delete',

//        'sliders-list' => 'sliders_list',
//        'sliders-add' => 'sliders_add',
//        'sliders-edit' => 'sliders_edit',
//        'sliders-delete' => 'sliders_delete',

        'users-list' => 'users_list',
        'users-add' => 'users_add',
        'users-edit' => 'users_edit',
        'users-delete' => 'users_delete',

//        'chats-list' => 'chats_list',
//        'chats-add' => 'chats_add',
//        'chats-edit' => 'chats_edit',
//        'chats-delete' => 'chats_delete',

        'employees-list' => 'employees_list',
        'employees-add' => 'employees_add',
        'employees-edit' => 'employees_edit',
        'employees-delete' => 'employees_delete',

        'roles-list' => 'roles_list',
        'roles-add' => 'roles_add',
        'roles-edit' => 'roles_edit',
        'roles-delete' => 'roles_delete',

        'permissions-list' => 'permissions_list',
        'permissions-add' => 'permissions_add',
        'permissions-edit' => 'permissions_edit',
        'permissions-delete' => 'permissions_delete',

        'logos-list' => 'logos_list',
        'logos-add' => 'logos_add',
        'logos-edit' => 'logos_edit',
        'logos-delete' => 'logos_delete',

        'history_datas-list' => 'history_datas_list',
        'history_datas-add' => 'history_datas_add',
        'history_datas-edit' => 'history_datas_edit',
        'history_datas-delete' => 'history_datas_delete',

        'settings-list' => 'settings_list',
        'settings-add' => 'settings_add',
        'settings-edit' => 'settings_edit',
        'settings-delete' => 'settings_delete',

        'job_notifications-list' => 'job_notifications_list',
        'job_notifications-add' => 'job_notifications_add',
        'job_notifications-edit' => 'job_notifications_edit',
        'job_notifications-delete' => 'job_notifications_delete',

//        'category_news-list' => 'category_news_list',
//        'category_news-add' => 'category_news_add',
//        'category_news-edit' => 'category_news_edit',
//        'category_news-delete' => 'category_news_delete',
//
//        'categories-list' => 'categories_list',
//        'categories-add' => 'categories_add',
//        'categories-edit' => 'categories_edit',
//        'categories-delete' => 'categories_delete',
//
//        'system_branches-list' => 'system_branches_list',
//        'system_branches-add' => 'system_branches_add',
//        'system_branches-edit' => 'system_branches_edit',
//        'system_branches-delete' => 'system_branches_delete',
//
//        'quotations-list' => 'quotations_list',
//        'quotations-add' => 'quotations_add',
//        'quotations-edit' => 'quotations_edit',
//        'quotations-delete' => 'quotations_delete',
//
//        'calendars-list' => 'calendars_list',
//        'calendars-add' => 'calendars_add',
//        'calendars-edit' => 'calendars_edit',
//        'calendars-delete' => 'calendars_delete',
//
//        'orders-list' => 'orders_list',
//        'orders-add' => 'orders_add',
//        'orders-edit' => 'orders_edit',
//        'orders-delete' => 'orders_delete',
//
//        'vouchers-list' => 'vouchers_list',
//        'vouchers-add' => 'vouchers_add',
//        'vouchers-edit' => 'vouchers_edit',
//        'vouchers-delete' => 'vouchers_delete',

        'websites-list' => 'websites_list',
        'websites-add' => 'websites_add',
        'websites-edit' => 'websites_edit',
        'websites-delete' => 'websites_delete',

//        'type_categorys-list' => 'type_categorys_list',
//        'type_categorys-add' => 'type_categorys_add',
//        'type_categorys-edit' => 'type_categorys_edit',
//        'type_categorys-delete' => 'type_categorys_delete',

        'advertises-list' => 'advertises_list',
        'advertises-add' => 'advertises_add',
        'advertises-edit' => 'advertises_edit',
        'advertises-delete' => 'advertises_delete',
        'advertises-config' => 'advertises_config',

        'type_adv-list' => 'type_adv_list',
        'type_adv-add' => 'type_adv_add',
        'type_adv-edit' => 'type_adv_edit',
        'type_adv-delete' => 'type_adv_delete',

        'contacts-list' => 'contacts_list',
        'contacts-add' => 'contacts_add',
        'contacts-edit' => 'contacts_edit',
        'contacts-delete' => 'contacts_delete',

        'reports-list' => 'reports_list',
        'reports-add' => 'reports_add',
        'reports-edit' => 'reports_edit',
        'reports-delete' => 'reports_delete',

        'withdraw_users-list' => 'withdraw_users_list',
        'withdraw_users-add' => 'withdraw_users_add',
        'withdraw_users-edit' => 'withdraw_users_edit',
        'withdraw_users-delete' => 'withdraw_users_delete',

        'ads-list' => 'ads_list',
        'ads-add' => 'ads_add',
        'ads-edit' => 'ads_edit',
        'ads-delete' => 'ads_delete',

        'partners-list' => 'partners_list',
        'partners-add' => 'partners_add',
        'partners-edit' => 'partners_edit',
        'partners-delete' => 'partners_delete',

    ],
    'table_module'=>[
        'dashboard',
        'job_emails',
//        'news',
//        'sliders',
        'users',
//        'chats',
        'employees',
        'roles',
        'permissions',
        'logos',
        'history_datas',
        'settings',
        'job_notifications',
//        'category_news',
//        'categories',
//        'system_branches',
//        'quotations',
//        'calendars',
//        'orders',
//        'vouchers',
        'websites',
//        'type_categories',
        'advertises',
        'type_advs',
        'contacts',
        'reports',
        'withdraw_users',
        'ads',
        'partners',
    ],

    'table_module_name'=>[
        'Dashboard',
        'Job Email',
//        'Tin tức',
//        'Slider',
        'Publisher',
//        'Chat',
        'Nhân viên',
        'Vai trò nhân viên',
        'Cấp quyền',
        'Logo',
        'Lịch sử dữ liệu',
        'Cài đặt',
        'Thông báo',
//        'Danh mục tin tức',
//        'Danh mục sản phẩm',
//        'Danh sách cửa hàng',
//        'Các câu danh ngôn',
//        'Quản lý lịch',
//        'Quản lý đơn hàng',
//        'Quản lý mã giảm giá',
        'Websites',
//        'Quản lý loại website',
        'Zones',
        'Quản lý loại quảng cáo',
        'Message',
        'Report',
        'Wallet',
        'Ads',
        'Partner',
    ],

    'module_children'=>[
        'list',
        'add',
        'edit',
        'delete',
    ]
];
